// UI TYPES
export const DIGITAL_CONTENT_AVAILABLE = Object.freeze({
  ARTIFICIAL_INTELLIGENCE: "ARTIFICIAL_INTELLIGENCE",
  DATA_SCIENCE: "DATA_SCIENCE",
  CLOUD_COMPUTING: "CLOUD_COMPUTING",
  QUANTUM_COMPUTING: "QUANTUM_COMPUTING",
  OTHER: "OTHER",
});

export const DIGITAL_CONTENT_SELECTED = "DIGITAL_CONTENT_SELECTED";
