// UI TYPES
export const DIGITAL_CONTENT_AVAILABLE = Object.freeze({
  ARTIFICIAL_INTELLIGENCE: "Artificial Intelligence",
  DATA_SCIENCE: "Data Science",
  CLOUD_COMPUTING: "Cloud Computing",
  QUANTUM_COMPUTING: "Quantum Computing",
  OTHER_TECHNOLOGIES: "Other",
});

export const DIGITAL_CONTENT_SELECTED = "DIGITAL_CONTENT_SELECTED";

export const DIGITAL_CONTENT_FILTERED = "DIGITAL_CONTENT_FILTERED";

export const BLOG_POST_SELECTED = "BLOG_POST_SELECTED";

export const VIDEO_SELECTED = "VIDEO_SELECTED";
